stages:
  - tagChecking
  - build
  - test
  - sonarqube
  - deploy
  - e2eTests

tag-checker:
  stage: tagChecking
  script:
    - python3 tag_checker.py $CI_COMMIT_TAG
  only:
    - tags

junit:
  stage: test
  script:
    - ./gradlew test
    - ls ./build/jacoco
  artifacts:
    paths:
      - build/jacoco/test-report.xml

sonarqube-report:
  stage: sonarqube
  script:
    ./gradlew sonarqube

integration-tests:
  stage: test
  script:
    - ./gradlew integration

# builds all branches, except dev and master
branch-build:
  stage: build
  script:
    - ./gradlew bootJar
  artifacts:
    paths:
      - build/libs
  except:
    - tags
    - master
    - dev

deploy-staging:
  stage: deploy
  script:
    - ./gradlew bootJar
    - rm -rf /home/gitlab-runner/staging/ || true
    - mkdir /home/gitlab-runner/staging/
    - cp -r ./build/libs /home/gitlab-runner/staging
    - cp runner-scripts/staging.sh /home/gitlab-runner/staging.sh
    - chmod u+x /home/gitlab-runner/staging.sh
    - echo "export MARIADB_USERNAME=${MARIADB_USERNAME}" > /home/gitlab-runner/staging/env.sh
    - echo "export MARIADB_PASSWORD=${MARIADB_PASSWORD}" >> /home/gitlab-runner/staging/env.sh
    - echo "export GMAIL_USERNAME=${GMAIL_USERNAME}" >> /home/gitlab-runner/staging/env.sh
    - echo "export GMAIL_PASSWORD=${GMAIL_PASSWORD}" >> /home/gitlab-runner/staging/env.sh
    - echo "export OPS_API_KEY=${OPS_API_KEY}" >> /home/gitlab-runner/staging/env.sh
    - echo "export OPS_COLAB_KEY=${OPS_COLAB_KEY}" >> /home/gitlab-runner/staging/env.sh
    - sudo systemctl restart staging-tab
  artifacts:
    paths:
      - build/libs
  only:
    - dev

deploy-production:
  stage: deploy
  script:
    - ./gradlew bootJar
    - rm -rf /home/gitlab-runner/production/ || true
    - mkdir /home/gitlab-runner/production/
    - cp -r ./build/libs /home/gitlab-runner/production
    - cp runner-scripts/production.sh /home/gitlab-runner/production.sh
    - chmod u+x /home/gitlab-runner/production.sh
    - echo "export MARIADB_USERNAME=${MARIADB_USERNAME}" > /home/gitlab-runner/production/env.sh
    - echo "export MARIADB_PASSWORD=${MARIADB_PASSWORD}" >> /home/gitlab-runner/production/env.sh
    - echo "export GMAIL_USERNAME=${GMAIL_USERNAME}" >> /home/gitlab-runner/production/env.sh
    - echo "export GMAIL_PASSWORD=${GMAIL_PASSWORD}" >> /home/gitlab-runner/production/env.sh
    - echo "export OPS_API_KEY=${OPS_API_KEY}" >> /home/gitlab-runner/production/env.sh
    - echo "export OPS_COLAB_KEY=${OPS_COLAB_KEY}" >> /home/gitlab-runner/production/env.sh
    - sudo systemctl restart production-tab
  artifacts:
    paths:
      - build/libs
  only:
    - tags

endToEndTests:
  stage: e2eTests
  script:
    - ./gradlew end2end
  only:
    - dev